export const TESTING = 'TESTING';
export const RESET_PROJECT_STATE = 'RESET_PROJECT_STATE';
export const RESET_TASK = 'RESET_TASK';
// export const TASK_STATE = 'TASK_STATE';
export const SET_ORGANISATION_ID='SET_ORGANISATION_ID'
export const ADD_ORGANISATION = 'ADD_ORGANISATION';
export const ADD_ORGANISATION_SUCCESS = 'ADD_ORGANISATION_SUCCESS';
export const ADD_ORGANISATION_FAILED = 'ADD_ORGANISATION_FAILED';

export const EDIT_ORGANISATION = 'EDIT_ORGANISATION';
export const EDIT_ORGANISATION_SUCCESS = 'EDIT_ORGANISATION_SUCCESS';
export const EDIT_ORGANISATION_FAILED = 'EDIT_ORGANISATION_FAILED';
 
export const GET_ALL_ORGANISATION = 'GET_ALL_ORGANISATION';
export const GET_ALL_ORGANISATION_SUCCESS = 'GET_ALL_ORGANISATION_SUCCESS';
export const GET_ALL_ORGANISATION_FAILED = 'GET_ALL_ORGANISATION_FAILED';
 
export const GET_ORGANISATION = 'GET_ORGANISATION';
export const GET_ORGANISATION_SUCCESS = 'GET_ORGANISATION_SUCCESS';
export const GET_ORGANISATION_FAILED = 'GET_ORGANISATION_FAILED';

export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED';

export const GET_TASK_STATUS = 'GET_TASK_STATUS';
export const GET_TASK_STATUS_SUCCESS = 'GET_TASK_STATUS_SUCCESS';
export const GET_TASK_STATUS_FAILED = 'GET_TASK_STATUS_FAILED';

export const TASK_STATE = 'TASK_STATE';
export const TASK_STATE_SUCCESS = 'TASK_STATE_SUCCESS';
export const TASK_STATE_FAILED = 'TASK_STATE_FAILED';

export const GET_TASK_LEVEL = 'GET_TASK_LEVEL';
export const GET_TASK_LEVEL_SUCCESS = 'GET_TASK_LEVEL_SUCCESS';
export const GET_TASK_LEVEL_FAILED = 'GET_TASK_LEVEL_FAILED';

export const GET_ALL_USER_OF_ROLE_USER = 'GET_ALL_USER_OF_ROLE_USER';
export const GET_ALL_USER_OF_ROLE_SUCCESS = 'GET_ALL_USER_OF_ROLE_SUCCESS';
export const GET_ALL_USER_OF_ROLE_FAILED = 'GET_ALL_USER_OF_ROLE_FAILED';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';
export const UPLOAD_PHOTO_FAILED = 'UPLOAD_PHOTO_FAILED';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILED = 'UPDATE_USER_PROFILE_FAILED';

export const UPDATE_USER = 'ADD_USER';
export const UPDATE_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'ADD_USER_FAILED';

export const GET_ALL_ROLES = 'GET_ROLES'
export const GET_ALL_ROLES_SUCCESS = 'GET_ROLES_SUCCESS'
export const GET_ALL_ROLES_FAILED = 'GET_ROLES_FAILED'

export const GET_ACCESS_TYPES = 'GET_ACCESS_TYPES'
export const GET_ACCESS_TYPES_SUCCESS = 'GET_ACCESS_TYPES_FAILURE'
export const GET_ACCESS_TYPES_FAILURE = 'GET_ACCESS_TYPES_FAILURE'

export const GET_ORG_ROLES = 'GET_ORG_ROLES'
export const GET_ORG_ROLES_SUCCESS = 'GET_ORG_ROLES_SUCCESS'
export const GET_ORG_ROLES_FAILED = 'GET_ORG_ROLES_FAILED'

export const GET_ROLE = 'GET_ROLE'
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS'
export const GET_ROLE_FAILED = 'GET_ROLE_FAILED'

export const ADD_ROLES = 'ADD_ROLES'
export const ADD_ROLES_SUCCESS = 'ADD_ROLES_SUCCESS'
export const ADD_ROLES_FAILED = 'ADD_ROLES_FAILED'

export const UPDATE_ROLES = 'UPDATE_ROLES'
export const UPDATE_ROLES_SUCCESS = 'UPDATE_ROLES_SUCCESS'
export const UPDATE_ROLES_FAILED = 'UPDATE_ROLES_FAILED'

export const LOGIN_ORGANISATION = 'LOGIN_ORGANISATION';
export const LOGIN_ORGANISATION_SUCCESS = 'LOGIN_ORGANISATION_SUCCESS';
export const LOGIN_ORGANISATION_FAILED = 'LOGIN_ORGANISATION_FAILED';
export const ORG_LOGIN_DB = 'ORG_LOGIN_DB';
 
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const CONFIRM_USER = 'CONFIRM_USER';
export const CONFIRM_USER_SUCCESS = 'CONFIRM_USER_SUCCESS';
export const CONFIRM_USER_FAILED = 'CONFIRM_USER_FAILED';

export const USER_AUTHENTICATION = 'USER_AUTHENTICATION';
export const USER_AUTHENTICATION_SUCCESS = 'USER_AUTHENTICATION_SUCCESS';
export const USER_AUTHENTICATION_FAILED = 'USER_AUTHENTICATION_FAILED';
 
export const GET_CODE = 'GET_CODE';
export const GET_CODE_SUCCESS = 'GET_CODE_SUCCESS';
export const GET_CODE_FAILED = 'GET_CODE_FAILED';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const CONFIRM_NEW_PASSWORD = 'CONFIRM_NEW_PASSWORD';
export const CONFIRM_NEW_PASSWORD_SUCCESS = 'CONFIRM_NEW_PASSWORD_SUCCESS';
export const CONFIRM_NEW_PASSWORD_FAILED = 'CONFIRM_NEW_PASSWORD_FAILED';

export const GET_PENDING_TASK = 'GET_PENDING_TASK';
export const GET_PENDING_TASK_SUCCESS = 'GET_PENDING_TASK_SUCCESS';
export const GET_PENDING_TASK_FAILED = 'GET_PENDING_TASK_FAILED';

export const UNLOCK_PENDING_TASK = 'UNLOCK_PENDING_TASK';
export const UNLOCK_PENDING_TASK_SUCCESS = 'UNLOCK_PENDING_TASK_SUCCESS';
export const UNLOCK_PENDING_TASK_FAILED = 'UNLOCK_PENDING_TASK_FAILED';

export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS';
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS';
export const GET_ALL_PROJECTS_FAILED = 'GET_ALL_PROJECTS_FAILED';

export const INSERT_LEVEL_DATA = 'INSERT_LEVEL_DATA';
export const INSERT_LEVEL_DATA_SUCCESS = 'INSERT_LEVEL_DATA_SUCCESS';
export const INSERT_LEVEL_DATA_FAILED = 'INSERT_LEVEL_DATA_FAILED';

export const GET_ALL_BATCHES = 'GET_ALL_BATCHES';
export const GET_ALL_BATCHES_SUCCESS = 'GET_ALL_BATCHES_SUCCESS';
export const GET_ALL_BATCHES_FAILED = 'GET_ALL_BATCHES_FAILED';

export const GET_SOURCE_LEVEL = 'GET_SOURCE_LEVEL';
export const GET_SOURCE_LEVEL_SUCCESS = 'GET_SOURCE_LEVEL_SUCCESS';
export const GET_SOURCE_LEVEL_FAILED = 'GET_SOURCE_LEVEL_FAILED';

export const INSERT_STATUS_DATA = 'INSERT_STATUS_DATA';
export const INSERT_STATUS_DATA_SUCCESS = 'INSERT_STATUS_DATA_SUCCESS';
export const INSERT_STATUS_DATA_FAILED = 'INSERT_STATUS_DATA_FAILED';
 
export const GET_BATCH_OUTPUT = 'GET_BATCH_OUTPUT';
export const GET_BATCH_OUTPUT_SUCCESS = 'GET_BATCH_OUTPUT_SUCCESS';
export const GET_BATCH_OUTPUT_FAILED = 'GET_BATCH_OUTPUT_FAILED';

export const GET_PROJECT_BATCH_STATUS = 'GET_PROJECT_BATCH_STATUS';
export const GET_PROJECT_BATCH_STATUS_SUCCESS = 'GET_PROJECT_BATCH_STATUS_SUCCESS';
export const GET_PROJECT_BATCH_STATUS_FAILED = 'GET_PROJECT_BATCH_STATUS_FAILED';

export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAILED = 'ADD_PROJECT_FAILED';

export const GET_PROJECT = 'GET_PROJECT';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAILED = 'GET_PROJECT_FAILED';

export const GET_ALL_PROJECT_USERS = 'GET_ALL_PROJECT_USERS';
export const GET_ALL_PROJECT_USERS_SUCCESS = 'GET_ALL_PROJECT_USERS_SUCCESS';
export const GET_ALL_PROJECT_USERS_FAILED = 'GET_ALL_PROJECT_USERS_FAILED';

export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';
export const DELETE_REQUEST_FAILED = 'DELETE_REQUEST_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const ADD_USERS_TO_PROJECT = 'ADD_USERS_TO_PROJECT';
export const ADD_USERS_TO_PROJECT_SUCCESS = 'ADD_USERS_TO_PROJECT_SUCCESS';
export const ADD_USERS_TO_PROJECT_FAILED = 'ADD_USERS_TO_PROJECT_FAILED';

export const EDIT_PROJECT = 'EDIT_PROJECT';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';
export const EDIT_PROJECT_FAILED = 'EDIT_PROJECT_FAILED';

export const LOGGED_IN_ORGANISATION_DETAIL = 'LOGGED_IN_ORGANISATION_DETAIL';

export const GET_ALL_FIELDS = 'GET_ALL_FIELDS';
export const GET_ALL_FIELDS_SUCCESS = 'GET_ALL_FIELDS_SUCCESS';
export const GET_ALL_FIELDS_FAILED = 'GET_ALL_FIELDS_FAILED';

export const ADD_FIELD = 'ADD_FIELD';
export const ADD_FIELD_SUCCESS = 'ADD_FIELD_SUCCESS';
export const ADD_FIELD_FAILED = 'ADD_FIELD_FAILED';

export const GET_PROJECT_FIELDS = 'GET_PROJECT_FIELDS';
export const GET_PROJECT_FIELDS_SUCCESS = 'GET_PROJECT_FIELDS_SUCCESS';
export const GET_PROJECT_FIELDS_FAILED = 'GET_PROJECT_FIELDS_FAILED';

export const GET_USER_TARGET = 'GET_USER_TARGET';
export const GET_USER_TARGET_SUCCESS = 'GET_USER_TARGET_SUCCESS';
export const GET_USER_TARGET_FAILED = 'GET_USER_TARGET_FAILED';

export const RESET_USER_TARGET = 'RESET_USER_TARGET';
export const RESET_USER_TARGET_SUCCESS = 'RESET_USER_TARGET_SUCCESS';
export const RESET_USER_TARGET_FAILED = 'RESET_USER_TARGET_FAILED';

export const SET_USER_LEVEL_TARGET = 'SET_USER_LEVEL_TARGET';
export const SET_USER_LEVEL_TARGET_SUCCESS = 'SET_USER_LEVEL_TARGET_SUCCESS';
export const SET_USER_LEVEL_TARGET_FAILED = 'SET_USER_LEVEL_TARGET_FAILED';

export const GET_PROJECT_RULES = 'GET_PROJECT_RULES';
export const GET_PROJECT_RULES_SUCCESS = 'GET_PROJECT_RULES_SUCCESS';
export const GET_PROJECT_RULES_FAILED = 'GET_PROJECT_RULES_FAILED';

export const DELETE_PROJECT_RULES = 'DELETE_PROJECT_RULES';
export const DELETE_PROJECT_RULES_SUCCESS = 'DELETE_PROJECT_RULES_SUCCESS';
export const DELETE_PROJECT_RULES_FAILED = 'DELETE_PROJECT_RULES_FAILED';

export const ADD_RULE_IN_PROJECT_LEVEL = 'ADD_RULE_IN_PROJECT_LEVEL';
export const ADD_RULE_IN_PROJECT_LEVEL_SUCCESS = 'ADD_RULE_IN_PROJECT_LEVEL_SUCCESS';
export const ADD_RULE_IN_PROJECT_LEVEL_FAILED = 'ADD_RULE_IN_PROJECT_LEVEL_FAILED';

export const UPDATE_RULE_IN_PROJECT_LEVEL = 'UPDATE_RULE_IN_PROJECT_LEVEL';
export const UPDATE_RULE_IN_PROJECT_LEVEL_SUCCESS = 'UPDATE_RULE_IN_PROJECT_LEVEL_SUCCESS';
export const UPDATE_RULE_IN_PROJECT_LEVEL_FAILED = 'UPDATE_RULE_IN_PROJECT_LEVEL_FAILED';

export const GET_PROJECT_BATCH = 'GET_PROJECT_BATCH';
export const GET_PROJECT_BATCH_SUCCESS = 'GET_PROJECT_BATCH_SUCCESS';
export const GET_PROJECT_BATCH_FAILED = 'GET_PROJECT_BATCH_FAILED';

export const ADD_PROJECT_BATCH = 'ADD_PROJECT_BATCH';
export const ADD_PROJECT_BATCH_SUCCESS = 'ADD_PROJECT_BATCH_SUCCESS';
export const ADD_PROJECT_BATCH_FAILED = 'ADD_PROJECT_BATCH_FAILED';

export const UPDATE_PROJECT_BATCH = 'UPDATE_PROJECT_BATCH';
export const UPDATE_PROJECT_BATCH_SUCCESS = 'UPDATE_PROJECT_BATCH_SUCCESS';
export const UPDATE_PROJECT_BATCH_FAILED = 'UPDATE_PROJECT_BATCH_FAILED';


export const GET_AD_USERS = 'GET_AD_USERS';
export const GET_AD_USERS_SUCCESS = 'GET_AD_USERS_SUCCESS';
export const GET_AD_USERS_FAILED = 'GET_AD_USERS_FAILED';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED';


export const UPDATE_FIELD = 'UPDATE_FIELD';
export const UPDATE_FIELD_SUCCESS = 'UPDATE_FIELD_SUCCESS';
export const UPDATE_FIELD_FAILED = 'UPDATE_FIELD_FAILED';

export const DELETE_FIELD = 'DELETE_FIELD';
export const DELETE_FIELD_SUCCESS = 'DELETE_FIELD_SUCCESS';
export const DELETE_FIELD_FAILED = 'DELETE_FIELD_FAILED';

export const GET_ALL_PRIVILEGES = 'GET_ALL_PRIVILEGES';
export const GET_ALL_PRIVILEGES_SUCCESS = 'GET_ALL_PRIVILEGES_SUCCESS';
export const GET_ALL_PRIVILEGES_FAILED = 'GET_ALL_PRIVILEGES_FAILED';

export const GET_CUSTOM_FIELD = 'GET_CUSTOM_FIELD';
export const GET_CUSTOM_FIELD_SUCCESS = 'GET_CUSTOM_FIELD_SUCCESS';
export const GET_CUSTOM_FIELD_FAILED = 'GET_CUSTOM_FIELD_FAILED';

export const CREATE_CUSTOM_FIELD = 'CREATE_CUSTOM_FIELD';
export const CREATE_CUSTOM_FIELD_SUCCESS = 'CREATE_CUSTOM_FIELD_SUCCESS';
export const CREATE_CUSTOM_FIELD_FAILED = 'CREATE_CUSTOM_FIELD_FAILED';

export const EDIT_CUSTOM_FIELD = 'EDIT_CUSTOM_FIELD';
export const EDIT_CUSTOM_FIELD_SUCCESS = 'EDIT_CUSTOM_FIELD_SUCCESS';
export const EDIT_CUSTOM_FIELD_FAILED = 'EDIT_CUSTOM_FIELD_FAILED';

export const STORE_FIELD_DATA = 'STORE_FIELD_DATA';

export const APPEND_CUSTOM_FIELD = 'APPEND_CUSTOM_FIELD';

export const MODIFY_STORE_FIELD = 'MODIFY_STORE_FIELD';


export const IMPORT_PROJECT_TASKS = 'IMPORT_PROJECT_TASKS';
export const IMPORT_PROJECT_TASKS_SUCCESS = 'IMPORT_PROJECT_TASKS_SUCCESS';
export const IMPORT_PROJECT_TASKS_FAILED = 'IMPORT_PROJECT_TASKS_FAILED';

export const PROJECT_BATCH_DELETE = 'PROJECT_BATCH_DELETE';
export const PROJECT_BATCH_DELETE_SUCCESS = 'PROJECT_BATCH_DELETE_SUCCESS';
export const PROJECT_BATCH_DELETE_FAILED = 'PROJECT_BATCH_DELETE_FAILED';

export const IMPORT_PROJECT_OUTPUT = 'IMPORT_PROJECT_OUTPUT';
export const IMPORT_PROJECT_OUTPUT_SUCCESS = 'IMPORT_PROJECT_OUTPUT_SUCCESS';
export const IMPORT_PROJECT_OUTPUT_FAILED = 'IMPORT_PROJECT_OUTPUT_FAILED';

export const RESET_IMPORT_PROJECT_TASKS = 'RESET_IMPORT_PROJECT_TASKS';

export const IMPORT_USERS_FROM_FILE = 'IMPORT_USERS_FROM_FILE';
export const IMPORT_USERS_FROM_FILE_SUCCESS = 'IMPORT_USERS_FROM_FILE_SUCCESS';
export const IMPORT_USERS_FROM_FILE_FAILED = 'IMPORT_USERS_FROM_FILE_FAILED';

export const GET_ALL_ORG_USERS = 'GET_ALL_ORG_USERS';
export const GET_ALL_ORG_USERS_SUCCESS = 'GET_ALL_ORG_USERS_SUCCESS';
export const GET_ALL_ORG_USERS_FAILED = 'GET_ALL_ORG_USERS_FAILED';

export const GET_ALL_PROJECT_ROLES = 'GET_ALL_PROJECT_ROLES';
export const GET_ALL_PROJECT_ROLES_SUCCESS = 'GET_ALL_PROJECT_ROLES_SUCCESS';
export const GET_ALL_PROJECT_ROLES_FAILED = 'GET_ALL_PROJECT_ROLES_FAILED';

export const GET_PROJECT_ROLES = 'GET_PROJECT_ROLES';
export const GET_PROJECT_ROLES_SUCCESS = 'GET_PROJECT_ROLES_SUCCESS';
export const GET_PROJECT_ROLES_FAILED = 'GET_PROJECT_ROLES_FAILED';

export const ADD_PROJECT_ROLES = 'ADD_PROJECT_ROLES';
export const ADD_PROJECT_ROLES_SUCCESS = 'ADD_PROJECT_ROLES_SUCCESS';
export const ADD_PROJECT_ROLES_FAILED = 'ADD_PROJECT_ROLES_FAILED';

export const DELETE_PROJECT_ROLES = 'DELETE_PROJECT_ROLES';
export const DELETE_PROJECT_ROLES_SUCCESS = 'DELETE_PROJECT_ROLES_SUCCESS';
export const DELETE_PROJECT_ROLES_FAILED = 'DELETE_PROJECT_ROLES_FAILED';

export const GET_PROJECT_ROLES_FOR_ORGANISATION = 'GET_PROJECT_ROLES_FOR_ORGANISATION';
export const GET_PROJECT_ROLES_FOR_ORGANISATION_SUCCESS = 'GET_PROJECT_ROLES_FOR_ORGANISATION_SUCCESS';
export const GET_PROJECT_ROLES_FOR_ORGANISATION_FAILED = 'GET_PROJECT_ROLES_FOR_ORGANISATION_FAILED';

export const ADD_PROJECT_ROLES_FOR_ORGANISATION = 'ADD_PROJECT_ROLES_FOR_ORGANISATION';
export const ADD_PROJECT_ROLES_FOR_ORGANISATION_SUCCESS = 'ADD_PROJECT_ROLES_FOR_ORGANISATION_SUCCESS';
export const ADD_PROJECT_ROLES_FOR_ORGANISATION_FAILED = 'ADD_PROJECT_ROLES_FOR_ORGANISATION_FAILED';

export const ADD_PROJECT_ROLES_LOCALLY = 'ADD_PROJECT_ROLES_LOCALLY';

export const GET_USER_PROJECTS = 'GET_USER_PROJECTS';
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS';
export const GET_USER_PROJECTS_FAILED = 'GET_USER_PROJECTS_FAILED';


export const GET_USER_TASKS_FOR_PROJECTS = 'GET_USER_TASKS_FOR_PROJECTS';
export const GET_USER_TASKS_FOR_PROJECTS_SUCCESS = 'GET_USER_TASKS_FOR_PROJECTS_SUCCESS';
export const GET_USER_TASKS_FOR_PROJECTS_FAILED = 'GET_USER_TASKS_FOR_PROJECTS_FAILED';

export const UPDATE_TASKS = 'UPDATE_TASKS';
export const UPDATE_TASKS_SUCCESS = 'UPDATE_TASKS_SUCCESS';
export const UPDATE_TASKS_FAILED = 'UPDATE_TASKS_FAILED';

export const IMPORT_LEVEL_PROJECT_USERS = 'IMPORT_LEVEL_PROJECT_USERS';
export const IMPORT_LEVEL_PROJECT_USERS_SUCCESS = 'IMPORT_LEVEL_PROJECT_USERS_SUCCESS';
export const IMPORT_LEVEL_PROJECT_USERS_FAILED = 'IMPORT_LEVEL_PROJECT_USERS_FAILED';

export const CLONE_PROJECT = 'CLONE_PROJECT';
export const CLONE_PROJECT_SUCCESS = 'CLONE_PROJECT_SUCCESS';
export const CLONE_PROJECT_FAILED = 'CLONE_PROJECT_FAILED';

export const GET_USER_PRIVILEGES = 'GET_USER_PRIVILEGES';
export const GET_USER_PRIVILEGES_SUCCESS = 'GET_USER_PRIVILEGES_SUCCESS';
export const GET_USER_PRIVILEGES_FAILED = 'GET_USER_PRIVILEGES_FAILED';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAILED = 'ADD_MESSAGE_FAILED';

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';

export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAILED = 'DELETE_MESSAGE_FAILED';

export const CHECK_EXCEL_PROGRESS = 'CHECK_EXCEL_PROGRESS';
export const CHECK_EXCEL_PROGRESS_SUCCESS = 'CHECK_EXCEL_PROGRESS_SUCCESS';
export const CHECK_EXCEL_PROGRESS_FAILED = 'CHECK_EXCEL_PROGRESS_FAILED';

export const CHECK_IMPORT_PROGRESS = 'CHECK_IMPORT_PROGRESS';
export const CHECK_IMPORT_PROGRESS_SUCCESS = 'CHECK_IMPORT_PROGRESS_SUCCESS';
export const CHECK_IMPORT_PROGRESS_FAILED = 'CHECK_IMPORT_PROGRESS_FAILED';

export const CURATION_UPLOAD_FILE = 'CURATION_UPLOAD_FILE';
export const CURATION_UPLOAD_FILE_SUCCESS = 'CURATION_UPLOAD_FILE_SUCCESS';
export const CURATION_UPLOAD_FILE_FAILED = 'CURATION_UPLOAD_FILE_FAILED';

export const GET_CURATION = 'GET_CURATION';
export const GET_CURATION_SUCCESS = 'GET_CURATION_SUCCESS';
export const GET_CURATION_FAILED = 'GET_CURATION_FAILED';

export const ADD_TAXONOMY = 'ADD_TAXONOMY';
export const ADD_TAXONOMY_SUCCESS = 'ADD_TAXONOMY_SUCCESS';
export const ADD_TAXONOMY_FAILED = 'ADD_TAXONOMY_FAILED';

export const TAXONOMY_UPLOAD_FILE = 'TAXONOMY_UPLOAD_FILE';
export const TAXONOMY_UPLOAD_FILE_SUCCESS = 'TAXONOMY_UPLOAD_FILE_SUCCESS';
export const TAXONOMY_UPLOAD_FILE_FAILED = 'TAXONOMY_UPLOAD_FILE_FAILED';

export const GET_PROJECT_TAXONOMY = 'GET_PROJECT_TAXONOMY';
export const GET_PROJECT_TAXONOMY_SUCCESS = 'GET_PROJECT_TAXONOMY_SUCCESS';
export const GET_PROJECT_TAXONOMY_FAILED = 'GET_PROJECT_TAXONOMY_FAILED';

export const GET_PROJECT_TAXONOMY_DETAIL = 'GET_PROJECT_TAXONOMY_DETAIL';
export const GET_PROJECT_TAXONOMY_DETAIL_SUCCESS = 'GET_PROJECT_TAXONOMY_DETAIL_SUCCESS';
export const GET_PROJECT_TAXONOMY_DETAIL_FAILED = 'GET_PROJECT_TAXONOMY_DETAIL_FAILED';

export const SEARCH_PROJECT_TAXONOMY = 'SEARCH_PROJECT_TAXONOMY';
export const SEARCH_PROJECT_TAXONOMY_SUCCESS = 'SEARCH_PROJECT_TAXONOMY_SUCCESS';
export const SEARCH_PROJECT_TAXONOMY_FAILED = 'SEARCH_PROJECT_TAXONOMY_FAILED';

export const RESET_PROJECT_TAXONOMY = 'RESET_PROJECT_TAXONOMY';
export const SKIP_TASKS_SUCCESS = 'SKIP_TASKS_SUCCESS';
export const SKIP_TASKS = 'SKIP_TASKS';
export const SKIP_TASKS_FAILED = 'SKIP_TASKS_FAILED';

export const GET_SKIPPED_TASKS = 'GET_SKIPPED_TASKS';
export const GET_SKIPPED_TASKS_SUCCESS = 'GET_SKIPPED_TASKS_SUCCESS';
export const GET_SKIPPED_TASKS_FAILED = 'GET_SKIPPED_TASKS_FAILED';

export const GET_AVG_USER_TARGET_REPORT = 'GET_AVG_USER_TARGET_REPORT';
export const GET_AVG_USER_TARGET_REPORT_SUCCESS = 'GET_AVG_USER_TARGET_REPORT_SUCCESS';
export const GET_AVG_USER_TARGET_REPORT_FAILED = 'GET_AVG_USER_TARGET_REPORT_FAILED';
export const RESET_TASK_FIELDS = 'RESET_TASK_FIELDS';

export const GET_TARGETS_FOR_USER = 'GET_TARGETS_FOR_USER';
export const GET_TARGETS_FOR_USER_SUCCESS = 'GET_TARGETS_FOR_USER_SUCCESS';
export const GET_TARGETS_FOR_USER_FAILED = 'GET_TARGETS_FOR_USER_FAILED';

export const GET_PROJECT_FILES = 'GET_PROJECT_FILES'
export const GET_PROJECT_FILES_SUCCESS = 'GET_PROJECT_FILES_SUCCESS'
export const GET_PROJECT_FILES_FAILED = 'GET_PROJECT_FILES_FAILED'

export const RESET_USER_DETAILS = "RESET_USER_DETAILS"

export const AUDIO_TASKS_SUCCESS = 'AUDIO_TASKS_SUCCESS';
export const AUDIO_TASKS = 'AUDIO_TASKS';
export const AUDIO_TASKS_FAILED = 'AUDIO_TASKS_FAILED';

export const SAVE_PROFILE_DATA = 'SAVE_PROFILE_DATA'
export const SAVE_PROFILE_DATA_SUCCESS = 'SAVE_PROFILE_DATA_SUCCESS'
export const SAVE_PROFILE_DATA_FAILED = 'SAVE_PROFILE_DATA_FAILED'

export const SAVE_PROFILE_UPLOAD_ID_DOC = 'SAVE_PROFILE_UPLOAD_ID_DOC'
export const SAVE_PROFILE_UPLOAD_ID_DOC_SUCCESS = 'SAVE_PROFILE_UPLOAD_ID_DOC_SUCCESS'
export const SAVE_PROFILE_UPLOAD_ID_DOC_FAILED = 'SAVE_PROFILE_UPLOAD_ID_DOC_FAILED'

export const SAVE_PROFILE_UPLOAD_ID_DETAIL = 'SAVE_PROFILE_UPLOAD_ID_DETAIL'
export const SAVE_PROFILE_UPLOAD_ID_DETAIL_SUCCESS = 'SAVE_PROFILE_UPLOAD_ID_DETAIL_SUCCESS'
export const SAVE_PROFILE_UPLOAD_ID_DETAIL_FAILED = 'SAVE_PROFILE_UPLOAD_ID_DETAIL_FAILED'

export const SAVE_PROFILE_BANK_DETAIL = 'SAVE_PROFILE_BANK_DETAIL';
export const SAVE_PROFILE_BANK_DETAIL_SUCCESS = 'SAVE_PROFILE_BANK_DETAIL_SUCCESS'
export const SAVE_PROFILE_BANK_DETAIL_FAILED = 'SAVE_PROFILE_BANK_DETAIL_FAILED'

export const SAVE_PROFILE_UPLOAD_RESUME = 'SAVE_PROFILE_UPLOAD_RESUME';
export const SAVE_PROFILE_UPLOAD_RESUME_SUCCESS = 'SAVE_PROFILE_UPLOAD_RESUME_SUCCESS'
export const SAVE_PROFILE_UPLOAD_RESUME_FAILED = 'SAVE_PROFILE_UPLOAD_RESUME_FAILED'

export const SAVE_PROFILE_UPLOAD_RESUME_DETAIL = 'SAVE_PROFILE_UPLOAD_RESUME_DETAIL';
export const SAVE_PROFILE_UPLOAD_RESUME_DETAIL_SUCCESS = 'SAVE_PROFILE_UPLOAD_RESUME_DETAIL_SUCCESS';
export const SAVE_PROFILE_UPLOAD_RESUME_DETAIL_FAILED = 'SAVE_PROFILE_UPLOAD_RESUME_DETAIL_FAILED';

export const PLATFORM_SETUP_UPLOAD_VIDEO_FILE = 'PLATFORM_SETUP_UPLOAD_VIDEO_FILE';
export const PLATFORM_SETUP_UPLOAD_VIDEO_FILE_SUCCESS = 'PLATFORM_SETUP_UPLOAD_VIDEO_FILE_SUCCESS';
export const PLATFORM_SETUP_UPLOAD_VIDEO_FILE_FAILED = 'PLATFORM_SETUP_UPLOAD_VIDEO_FILE_FAILED';

export const PLATFORM_SETUP_UPLOAD_DOC_FILE = 'PLATFORM_SETUP_UPLOAD_DOC_FILE';
export const PLATFORM_SETUP_UPLOAD_DOC_FILE_SUCCESS = 'PLATFORM_SETUP_UPLOAD_DOC_FILE_SUCCESS';
export const PLATFORM_SETUP_UPLOAD_DOC_FILE_FAILED = 'PLATFORM_SETUP_UPLOAD_DOC_FILE_FAILED';

export const PLATFORM_SETUP_UPLOAD_TEST_IMPORT_FILE = 'PLATFORM_SETUP_UPLOAD_TEST_IMPORT_FILE';
export const PLATFORM_SETUP_UPLOAD_TEST_IMPORT_FILE_SUCCESS = 'PLATFORM_SETUP_UPLOAD_TEST_IMPORT_FILE_SUCCESS';
export const PLATFORM_SETUP_UPLOAD_TEST_IMPORT_FILE_FAILED = 'PLATFORM_SETUP_UPLOAD_TEST_IMPORT_FILE_FAILED';

export const GET_ORG_REPORT_DATA = 'GET_ORG_REPORT_DATA';
export const GET_ORG_REPORT_DATA_SUCCESS = 'GET_ORG_REPORT_DATA_SUCCESS';
export const GET_ORG_REPORT_DATA_FAILED = 'GET_ORG_REPORT_DATA_FAILED';

export const GET_ORG_USER_TASK_ERROR = 'GET_ORG_USER_TASK_ERROR';
export const GET_ORG_USER_TASK_ERROR_SUCCESS = 'GET_ORG_USER_TASK_ERROR_SUCCESS';
export const GET_ORG_USER_TASK_ERROR_FAILED = 'GET_ORG_USER_TASK_ERROR_FAILED';

export const GET_ORG_USER_TASK_ACCURACY = 'GET_ORG_USER_TASK_ACCURACY';
export const GET_ORG_USER_TASK_ACCURACY_SUCCESS = 'GET_ORG_USER_TASK_ACCURACY_SUCCESS';
export const GET_ORG_USER_TASK_ACCURACY_FAILED = 'GET_ORG_USER_TASK_ACCURACY_FAILED';

export const GET_PROJECT_BATCH_REPORT = 'GET_PROJECT_BATCH_REPORT';
export const GET_PROJECT_BATCH_REPORT_SUCCESS = 'GET_PROJECT_BATCH_REPORT_SUCCESS';
export const GET_PROJECT_BATCH_REPORT_FAILED = 'GET_PROJECT_BATCH_REPORT_FAILED';

export const GET_USER_BATCH_REPORT = 'GET_USER_BATCH_REPORT';
export const GET_USER_BATCH_REPORT_SUCCESS = 'GET_USER_BATCH_REPORT_SUCCESS';
export const GET_USER_BATCH_REPORT_FAILED = 'GET_USER_BATCH_REPORT_FAILED';

export const GET_PROJECT_BATCH_TASK_AND_ERROR = 'GET_PROJECT_BATCH_TASK_AND_ERROR';
export const GET_PROJECT_BATCH_TASK_AND_ERROR_SUCCESS = 'GET_PROJECT_BATCH_TASK_AND_ERROR_SUCCESS';
export const GET_PROJECT_BATCH_TASK_AND_ERROR_FAILED = 'GET_PROJECT_BATCH_TASK_AND_ERROR_FAILED';

export const GET_COMPUTATION_LEVEL_SKILL = 'GET_COMPUTATION_LEVEL_SKILL';
export const GET_COMPUTATION_LEVEL_SKILL_SUCCESS = 'GET_COMPUTATION_LEVEL_SKILL_SUCCESS';
export const GET_COMPUTATION_LEVEL_SKILL_FAILED = 'GET_COMPUTATION_LEVEL_SKILL_FAILED';

export const ADD_COMPUTATION_LEVEL_SKILL = 'ADD_COMPUTATION_LEVEL_SKILL';
export const ADD_COMPUTATION_LEVEL_SKILL_SUCCESS = 'ADD_COMPUTATION_LEVEL_SKILL_SUCCESS';
export const ADD_COMPUTATION_LEVEL_SKILL_FAILED = 'ADD_COMPUTATION_LEVEL_SKILL_FAILED';

export const DELETE_COMPUTATION_LEVEL_SKILL = 'DELETE_COMPUTATION_LEVEL_SKILL';
export const DELETE_COMPUTATION_LEVEL_SKILL_SUCCESS = 'DELETE_COMPUTATION_LEVEL_SKILL_SUCCESS';
export const DELETE_COMPUTATION_LEVEL_SKILL_FAILED = 'DELETE_COMPUTATION_LEVEL_SKILL_FAILED';

export const GET_ALL_ORG_SKILL = 'GET_ALL_ORG_SKILL';
export const GET_ALL_ORG_SKILL_SUCCESS = 'GET_ALL_ORG_SKILL_SUCCESS';
export const GET_ALL_ORG_SKILL_FAILED = 'GET_ALL_ORG_SKILL_FAILED';

export const GET_CROWD_USER = 'GET_CROWD_USER';
export const GET_CROWD_USER_SUCCESS = 'GET_CROWD_USER_SUCCESS';
export const GET_CROWD_USER_FAILED = 'GET_CROWD_USER_FAILED';

export const UPDATE_LOCAL_PROFILE_DATA = 'UPDATE_LOCAL_PROFILE_DATA'

export const ADD_SKILL = 'ADD_SKILL';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const ADD_SKILL_FAILED = 'ADD_SKILL_FAILED';

export const GET_SKILL = 'GET_SKILL';
export const GET_SKILL_SUCCESS = 'GET_SKILL_SUCCESS';
export const GET_SKILL_FAILED = 'GET_SKILL_FAILED';

export const SAVE_SKILL_MATERIAL = 'SAVE_SKILL_MATERIAL';
export const SAVE_SKILL_MATERIAL_SUCCESS = 'SAVE_SKILL_MATERIAL_SUCCESS';
export const SAVE_SKILL_MATERIAL_FAILED = 'SAVE_SKILL_MATERIAL_FAILED';

export const RESET_PLATFORM_SETUP = 'RESET_PLATFORM_SETUP';

export const GET_SKILL_MATERIAL = 'GET_SKILL_MATERIAL';
export const GET_SKILL_MATERIAL_SUCCESS = 'GET_SKILL_MATERIAL_SUCCESS';
export const GET_SKILL_MATERIAL_FAILED = 'GET_SKILL_MATERIAL_FAILED';

export const CREATE_TASKS = 'CREATE_TASKS';
export const CREATE_TASKS_SUCCESS = 'CREATE_TASKS_SUCCESS';
export const CREATE_TASKS_FAILED = 'CREATE_TASKS_FAILED';

export const ADD_COMPUTATION_LEVEL = 'ADD_COMPUTATION_LEVEL';
export const ADD_COMPUTATION_LEVEL_SUCCESS = 'ADD_COMPUTATION_LEVEL_SUCCESS';
export const ADD_COMPUTATION_LEVEL_FAILED = 'ADD_COMPUTATION_LEVEL_FAILED';

export const GET_USER_SKILL_MATERIAL = 'GET_USER_SKILL_MATERIAL';
export const GET_USER_SKILL_MATERIAL_SUCCESS = 'GET_USER_SKILL_MATERIAL_SUCCESS';
export const GET_USER_SKILL_MATERIAL_FAILED = 'GET_USER_SKILL_MATERIAL_FAILED';

export const SAVE_USER_TEST_DATA = 'SAVE_USER_TEST_DATA';
export const SAVE_USER_TEST_DATA_SUCCESS = 'SAVE_USER_TEST_DATA_SUCCESS';
export const SAVE_USER_TEST_DATA_FAILED = 'SAVE_USER_TEST_DATA_FAILED';

export const GET_USER_SKILL = 'GET_USER_SKILL';
export const GET_USER_SKILL_SUCCESS = 'GET_USER_SKILL_SUCCESS';
export const GET_USER_SKILL_FAILED = 'GET_USER_SKILL_FAILED';

export const DELETE_SKILL_MATERIAL = 'DELETE_SKILL_MATERIAL';
export const DELETE_SKILL_MATERIAL_SUCCESS = 'DELETE_SKILL_MATERIAL_SUCCESS';
export const DELETE_SKILL_MATERIAL_FAILED = 'DELETE_SKILL_MATERIAL_FAILED';

export const GET_USER_MANDATORY_MATERIALS = 'GET_USER_MANDATORY_MATERIALS';
export const GET_USER_MANDATORY_MATERIALS_SUCCESS = 'GET_USER_MANDATORY_MATERIALS_SUCCESS';
export const GET_USER_MANDATORY_MATERIALS_FAILED = 'GET_USER_MANDATORY_MATERIALS_FAILED';

export const GET_USER_BASIC_SKILL = 'GET_USER_BASIC_SKILL';
export const GET_USER_BASIC_SKILL_SUCCESS = 'GET_USER_BASIC_SKILL_SUCCESS';
export const GET_USER_BASIC_SKILL_FAILED = 'GET_USER_BASIC_SKILL_FAILED';

export const ADD_USER_MANDATORY_SKILL = 'ADD_USER_MANDATORY_SKILL';
export const ADD_USER_MANDATORY_SKILL_SUCCESS = 'ADD_USER_MANDATORY_SKILL_SUCCESS';
export const ADD_USER_MANDATORY_SKILL_FAILED = 'ADD_USER_MANDATORY_SKILL_FAILED';

export const GET_USER_BULK_TASKS_FOR_PROJECTS = 'GET_USER_BULK_TASKS_FOR_PROJECTS';
export const GET_USER_BULK_TASKS_FOR_PROJECTS_SUCCESS = 'GET_USER_BULK_TASKS_FOR_PROJECTS_SUCCESS';
export const GET_USER_BULK_TASKS_FOR_PROJECTS_FAILED = 'GET_USER_BULK_TASKS_FOR_PROJECTS_FAILED';

export const GET_PROJECT_AUTOMATED_PROCESSORS = 'GET_PROJECT_AUTOMATED_PROCESSORS';
export const GET_PROJECT_AUTOMATED_PROCESSORS_SUCCESS = 'GET_PROJECT_AUTOMATED_PROCESSORS_SUCCESS';
export const GET_PROJECT_AUTOMATED_PROCESSORS_FAILED = 'GET_PROJECT_AUTOMATED_PROCESSORS_FAILED';

export const DELETE_PROJECT_AUTOMATED_PROCESSOR = 'DELETE_PROJECT_AUTOMATED_PROCESSOR';
export const DELETE_PROJECT_AUTOMATED_PROCESSOR_SUCCESS = 'DELETE_PROJECT_AUTOMATED_PROCESSOR_SUCCESS';
export const DELETE_PROJECT_AUTOMATED_PROCESSOR_FAILED = 'DELETE_PROJECT_AUTOMATED_PROCESSOR_FAILED';4

export const GET_PROJECT_RUNNER_TYPE = 'GET_PROJECT_RUNNER_TYPE';
export const GET_PROJECT_RUNNER_TYPE_SUCCESS = 'GET_PROJECT_RUNNER_TYPE_SUCCESS';
export const GET_PROJECT_RUNNER_TYPE_FAILED = 'GET_PROJECT_RUNNER_TYPE_FAILED';

export const GET_PROJECT_AUTOMATED_PROCESSORS_LIST = 'GET_PROJECT_AUTOMATED_PROCESSORS_LIST';
export const GET_PROJECT_AUTOMATED_PROCESSORS_LIST_SUCCESS = 'GET_PROJECT_AUTOMATED_PROCESSORS_LIST_SUCCESS';
export const GET_PROJECT_AUTOMATED_PROCESSORS_LIST_FAILED = 'GET_PROJECT_AUTOMATED_PROCESSORS_LIST_FAILED';

export const ADD_PROJECT_AUTOMATED_PROCESSORS = 'ADD_PROJECT_AUTOMATED_PROCESSORS';
export const ADD_PROJECT_AUTOMATED_PROCESSORS_SUCCESS = 'ADD_PROJECT_AUTOMATED_PROCESSORS_SUCCESS';
export const ADD_PROJECT_AUTOMATED_PROCESSORS_FAILED = 'ADD_PROJECT_AUTOMATED_PROCESSORS_FAILED';

export const UPDATE_PROJECT_AUTOMATED_PROCESSORS = 'UPDATE_PROJECT_AUTOMATED_PROCESSORS';
export const UPDATE_PROJECT_AUTOMATED_PROCESSORS_SUCCESS = 'UPDATE_PROJECT_AUTOMATED_PROCESSORS_SUCCESS';
export const UPDATE_PROJECT_AUTOMATED_PROCESSORS_FAILED = 'UPDATE_PROJECT_AUTOMATED_PROCESSORS_FAILED';

export const GET_USER_VIEW_MANDATORY_MATERIALS = 'GET_USER_VIEW_MANDATORY_MATERIALS';
export const GET_USER_VIEW_MANDATORY_MATERIALS_SUCCESS = 'GET_USER_VIEW_MANDATORY_MATERIALS_SUCCESS';
export const GET_USER_VIEW_MANDATORY_MATERIALS_FAILED = 'GET_USER_VIEW_MANDATORY_MATERIALS_FAILED';

export const GET_USER_ADVANCED_SKILL = 'GET_USER_ADVANCED_SKILL';
export const GET_USER_ADVANCED_SKILL_SUCCESS = 'GET_USER_ADVANCED_SKILL_SUCCESS';
export const GET_USER_ADVANCED_SKILL_FAILED = 'GET_USER_ADVANCED_SKILL_FAILED';

export const GET_PROJECT_USER_SUMMARY = 'GET_PROJECT_USER_SUMMARY';
export const GET_PROJECT_USER_SUMMARY_SUCCESS = 'GET_PROJECT_USER_SUMMARY_SUCCESS';
export const GET_PROJECT_USER_SUMMARY_FAILED = 'GET_PROJECT_USER_SUMMARY_FAILED';

export const RESET_FIELD_STATE = 'RESET_FIELD_STATE'

export const GET_PROJECT_SPLIT_TASKS = 'GET_PROJECT_SPLIT_TASKS';
export const GET_PROJECT_SPLIT_TASKS_SUCCESS = 'GET_PROJECT_SPLIT_TASKS_SUCCESS';
export const GET_PROJECT_SPLIT_TASKS_FAILED = 'GET_PROJECT_SPLIT_TASKS_FAILED';

export const GET_SPLIT_TASKS_TYPES = 'GET_SPLIT_TASKS_TYPES';
export const GET_SPLIT_TASKS_TYPES_SUCCESS = 'GET_SPLIT_TASKS_TYPES_SUCCESS';
export const GET_SPLIT_TASKS_TYPES_FAILED = 'GET_SPLIT_TASKS_TYPES_FAILED';

export const DELETE_PROJECT_SPLIT_TASKS = 'DELETE_PROJECT_SPLIT_TASKS';
export const DELETE_PROJECT_SPLIT_TASKS_SUCCESS = 'DELETE_PROJECT_SPLIT_TASKS_SUCCESS';
export const DELETE_PROJECT_SPLIT_TASKS_FAILED = 'DELETE_PROJECT_SPLIT_TASKS_FAILED';

export const ADD_PROJECT_SPLIT_TASKS = 'ADD_PROJECT_SPLIT_TASKS';
export const ADD_PROJECT_SPLIT_TASKS_SUCCESS = 'ADD_PROJECT_SPLIT_TASKS_SUCCESS';
export const ADD_PROJECT_SPLIT_TASKS_FAILED = 'ADD_PROJECT_SPLIT_TASKS_FAILED';

export const UPDATE_PROJECT_SPLIT_TASKS = 'UPDATE_PROJECT_SPLIT_TASKS';
export const UPDATE_PROJECT_SPLIT_TASKS_SUCCESS = 'UPDATE_PROJECT_SPLIT_TASKS_SUCCESS';
export const UPDATE_PROJECT_SPLIT_TASKS_FAILED = 'UPDATE_PROJECT_SPLIT_TASKS_FAILED';

export const RESET_USER_TASKS_DATA_FOR_PROJECTS = 'RESET_USER_TASKS_DATA_FOR_PROJECTS'

export const GET_BATCH_OUTPUT_SELECTED = 'GET_BATCH_OUTPUT_SELECTED';
export const GET_BATCH_OUTPUT_SELECTED_SUCCESS = 'GET_BATCH_OUTPUT_SELECTED_SUCCESS';
export const GET_BATCH_OUTPUT_SELECTED_FAILED = 'GET_BATCH_OUTPUT_SELECTED_FAILED';

export const CHECK_USER_EXIST = 'CHECK_USER_EXIST';
export const CHECK_USER_EXIST_SUCCESS = 'CHECK_USER_EXIST_SUCCESS';
export const CHECK_USER_EXIST_FAILED = 'CHECK_USER_EXIST_FAILED';

export const GET_INCORRECT_TAXONOMY = "GET_INCORRECT_TAXONOMY";
export const GET_INCORRECT_TAXONOMY_SUCCESS = "GET_INCORRECT_TAXONOMY_SUCCESS";
export const GET_INCORRECT_TAXONOMY_FAILED = "GET_INCORRECT_TAXONOMY_FAILED";


